// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9y2GRaxUouH6R98jYDlPXg2UvWLhExMo',
    appId: '1:716861651082:web:e55f0a705bf2801e48d573',
    messagingSenderId: '716861651082',
    projectId: 'cpastone-cau-helpclosing',
    authDomain: 'cpastone-cau-helpclosing.firebaseapp.com',
    databaseURL: 'https://cpastone-cau-helpclosing-default-rtdb.firebaseio.com',
    storageBucket: 'cpastone-cau-helpclosing.appspot.com',
    measurementId: 'G-HYM4NW5XV7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7c1VGlOBHn_U-tuaF5bGZ-lHfX0NuSvI',
    appId: '1:716861651082:android:60c86fd4f1ee477b48d573',
    messagingSenderId: '716861651082',
    projectId: 'cpastone-cau-helpclosing',
    databaseURL: 'https://cpastone-cau-helpclosing-default-rtdb.firebaseio.com',
    storageBucket: 'cpastone-cau-helpclosing.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcboq-aaWrmE8fexT1dAkg0s_R9_K-0jE',
    appId: '1:716861651082:ios:77cfb4a5da42af3248d573',
    messagingSenderId: '716861651082',
    projectId: 'cpastone-cau-helpclosing',
    databaseURL: 'https://cpastone-cau-helpclosing-default-rtdb.firebaseio.com',
    storageBucket: 'cpastone-cau-helpclosing.appspot.com',
    iosClientId: '716861651082-dmj2vrohrv0jq3kufqgmpckcb9s2i5ph.apps.googleusercontent.com',
    iosBundleId: 'com.example.helpClosingFrontend',
  );
}
